apiVersion: v1
kind: Service
metadata:
  name: {{ include "distkv.fullname" . }}
  labels:
    {{- include "distkv.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  selector:
    {{- include "distkv.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
