// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/distkv.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType distinguishes the kind of log entry.
type EntryType int32

const (
	EntryType_ENTRY_NORMAL      EntryType = 0
	EntryType_ENTRY_CONF_CHANGE EntryType = 1
	EntryType_ENTRY_NOOP        EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_NORMAL",
		1: "ENTRY_CONF_CHANGE",
		2: "ENTRY_NOOP",
	}
	EntryType_value = map[string]int32{
		"ENTRY_NORMAL":      0,
		"ENTRY_CONF_CHANGE": 1,
		"ENTRY_NOOP":        2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_distkv_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_api_distkv_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{0}
}

// MsgType identifies the kind of Raft RPC message.
type MsgType int32

const (
	MsgType_MSG_REQUEST_VOTE          MsgType = 0
	MsgType_MSG_REQUEST_VOTE_RESP     MsgType = 1
	MsgType_MSG_APPEND_ENTRIES        MsgType = 2
	MsgType_MSG_APPEND_ENTRIES_RESP   MsgType = 3
	MsgType_MSG_INSTALL_SNAPSHOT      MsgType = 4
	MsgType_MSG_INSTALL_SNAPSHOT_RESP MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_REQUEST_VOTE",
		1: "MSG_REQUEST_VOTE_RESP",
		2: "MSG_APPEND_ENTRIES",
		3: "MSG_APPEND_ENTRIES_RESP",
		4: "MSG_INSTALL_SNAPSHOT",
		5: "MSG_INSTALL_SNAPSHOT_RESP",
	}
	MsgType_value = map[string]int32{
		"MSG_REQUEST_VOTE":          0,
		"MSG_REQUEST_VOTE_RESP":     1,
		"MSG_APPEND_ENTRIES":        2,
		"MSG_APPEND_ENTRIES_RESP":   3,
		"MSG_INSTALL_SNAPSHOT":      4,
		"MSG_INSTALL_SNAPSHOT_RESP": 5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_distkv_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_api_distkv_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{1}
}

// LogEntry is a single entry in the Raft log.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=distkv.EntryType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_distkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_NORMAL
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Snapshot holds a point-in-time snapshot of the state machine.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_distkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Snapshot) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message is the wire representation of a raft.Message, used for internal
// Raft RPCs between cluster members.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=distkv.MsgType" json:"type,omitempty"`
	From  string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To    string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Term  uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	// RequestVote fields.
	LastLogIndex uint64 `protobuf:"varint,5,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm  uint64 `protobuf:"varint,6,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	VoteGranted  bool   `protobuf:"varint,7,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	// AppendEntries fields.
	PrevLogIndex  uint64      `protobuf:"varint,8,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64      `protobuf:"varint,9,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	LeaderCommit  uint64      `protobuf:"varint,10,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	Entries       []*LogEntry `protobuf:"bytes,11,rep,name=entries,proto3" json:"entries,omitempty"`
	Success       bool        `protobuf:"varint,12,opt,name=success,proto3" json:"success,omitempty"`
	ConflictIndex uint64      `protobuf:"varint,13,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	ConflictTerm  uint64      `protobuf:"varint,14,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	// InstallSnapshot field.
	Snapshot *Snapshot `protobuf:"bytes,15,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// ReadIndex piggyback.
	ReadId        uint64 `protobuf:"varint,16,opt,name=read_id,json=readId,proto3" json:"read_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_distkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_REQUEST_VOTE
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *Message) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *Message) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *Message) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *Message) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *Message) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *Message) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Message) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *Message) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *Message) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Message) GetReadId() uint64 {
	if x != nil {
		return x.ReadId
	}
	return 0
}

// PutReq is the request for a Put operation.
type PutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReq) Reset() {
	*x = PutReq{}
	mi := &file_api_distkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReq) ProtoMessage() {}

func (x *PutReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReq.ProtoReflect.Descriptor instead.
func (*PutReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{3}
}

func (x *PutReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PutResp is the response for a Put operation.
type PutResp struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// leader_hint is the address of the current leader, if known, so the client
	// can redirect.
	LeaderHint    string `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResp) Reset() {
	*x = PutResp{}
	mi := &file_api_distkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResp) ProtoMessage() {}

func (x *PutResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResp.ProtoReflect.Descriptor instead.
func (*PutResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{4}
}

func (x *PutResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutResp) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

// GetReq is the request for a Get operation.
type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_api_distkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{5}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResp is the response for a Get operation.
type GetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_api_distkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{6}
}

func (x *GetResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// DeleteReq is the request for a Delete operation.
type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_api_distkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResp is the response for a Delete operation.
type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_api_distkv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResp) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

// CASReq is the request for a compare-and-swap operation.
type CASReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectValue   []byte                 `protobuf:"bytes,2,opt,name=expect_value,json=expectValue,proto3" json:"expect_value,omitempty"`
	NewValue      []byte                 `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASReq) Reset() {
	*x = CASReq{}
	mi := &file_api_distkv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASReq) ProtoMessage() {}

func (x *CASReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASReq.ProtoReflect.Descriptor instead.
func (*CASReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{9}
}

func (x *CASReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CASReq) GetExpectValue() []byte {
	if x != nil {
		return x.ExpectValue
	}
	return nil
}

func (x *CASReq) GetNewValue() []byte {
	if x != nil {
		return x.NewValue
	}
	return nil
}

// CASResp is the response for a compare-and-swap operation.
type CASResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASResp) Reset() {
	*x = CASResp{}
	mi := &file_api_distkv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASResp) ProtoMessage() {}

func (x *CASResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASResp.ProtoReflect.Descriptor instead.
func (*CASResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{10}
}

func (x *CASResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CASResp) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

// StatusReq is the request for cluster status.
type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_api_distkv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{11}
}

// StatusResp contains current cluster status.
type StatusResp struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	LeaderId string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Term     uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// role is the self-reported role of the node: "leader", "follower", or
	// "candidate".
	Role          string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CommitIndex   uint64   `protobuf:"varint,4,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	MemberIds     []string `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_api_distkv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResp) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StatusResp) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StatusResp) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResp) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// AddNodeReq requests that a new node be added to the cluster.
type AddNodeReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// addr is the network address of the new node.
	Addr          string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeReq) Reset() {
	*x = AddNodeReq{}
	mi := &file_api_distkv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeReq) ProtoMessage() {}

func (x *AddNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeReq.ProtoReflect.Descriptor instead.
func (*AddNodeReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{13}
}

func (x *AddNodeReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddNodeReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// AddNodeResp is the response for an AddNode operation.
type AddNodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResp) Reset() {
	*x = AddNodeResp{}
	mi := &file_api_distkv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResp) ProtoMessage() {}

func (x *AddNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResp.ProtoReflect.Descriptor instead.
func (*AddNodeResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{14}
}

func (x *AddNodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddNodeResp) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

// RemoveNodeReq requests that a node be removed from the cluster.
type RemoveNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeReq) Reset() {
	*x = RemoveNodeReq{}
	mi := &file_api_distkv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeReq) ProtoMessage() {}

func (x *RemoveNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeReq.ProtoReflect.Descriptor instead.
func (*RemoveNodeReq) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveNodeReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// RemoveNodeResp is the response for a RemoveNode operation.
type RemoveNodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResp) Reset() {
	*x = RemoveNodeResp{}
	mi := &file_api_distkv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResp) ProtoMessage() {}

func (x *RemoveNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_distkv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResp.ProtoReflect.Descriptor instead.
func (*RemoveNodeResp) Descriptor() ([]byte, []int) {
	return file_api_distkv_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveNodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveNodeResp) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

var File_api_distkv_proto protoreflect.FileDescriptor

const file_api_distkv_proto_rawDesc = "" +
	"\n" +
	"\x10api/distkv.proto\x12\x06distkv\"o\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.distkv.EntryTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"H\n" +
	"\bSnapshot\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x9b\x04\n" +
	"\aMessage\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.distkv.MsgTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12$\n" +
	"\x0elast_log_index\x18\x05 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x06 \x01(\x04R\vlastLogTerm\x12!\n" +
	"\fvote_granted\x18\a \x01(\bR\vvoteGranted\x12$\n" +
	"\x0eprev_log_index\x18\b \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\t \x01(\x04R\vprevLogTerm\x12#\n" +
	"\rleader_commit\x18\n" +
	" \x01(\x04R\fleaderCommit\x12*\n" +
	"\aentries\x18\v \x03(\v2\x10.distkv.LogEntryR\aentries\x12\x18\n" +
	"\asuccess\x18\f \x01(\bR\asuccess\x12%\n" +
	"\x0econflict_index\x18\r \x01(\x04R\rconflictIndex\x12#\n" +
	"\rconflict_term\x18\x0e \x01(\x04R\fconflictTerm\x12,\n" +
	"\bsnapshot\x18\x0f \x01(\v2\x10.distkv.SnapshotR\bsnapshot\x12\x17\n" +
	"\aread_id\x18\x10 \x01(\x04R\x06readId\"0\n" +
	"\x06PutReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"D\n" +
	"\aPutResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint\"\x1a\n" +
	"\x06GetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"5\n" +
	"\aGetResp\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x1d\n" +
	"\tDeleteReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\n" +
	"DeleteResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint\"Z\n" +
	"\x06CASReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\fexpect_value\x18\x02 \x01(\fR\vexpectValue\x12\x1b\n" +
	"\tnew_value\x18\x03 \x01(\fR\bnewValue\"D\n" +
	"\aCASResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint\"\v\n" +
	"\tStatusReq\"\x93\x01\n" +
	"\n" +
	"StatusResp\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12!\n" +
	"\fcommit_index\x18\x04 \x01(\x04R\vcommitIndex\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\tR\tmemberIds\"9\n" +
	"\n" +
	"AddNodeReq\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"H\n" +
	"\vAddNodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint\"(\n" +
	"\rRemoveNodeReq\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"K\n" +
	"\x0eRemoveNodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint*D\n" +
	"\tEntryType\x12\x10\n" +
	"\fENTRY_NORMAL\x10\x00\x12\x15\n" +
	"\x11ENTRY_CONF_CHANGE\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTRY_NOOP\x10\x02*\xa8\x01\n" +
	"\aMsgType\x12\x14\n" +
	"\x10MSG_REQUEST_VOTE\x10\x00\x12\x19\n" +
	"\x15MSG_REQUEST_VOTE_RESP\x10\x01\x12\x16\n" +
	"\x12MSG_APPEND_ENTRIES\x10\x02\x12\x1b\n" +
	"\x17MSG_APPEND_ENTRIES_RESP\x10\x03\x12\x18\n" +
	"\x14MSG_INSTALL_SNAPSHOT\x10\x04\x12\x1d\n" +
	"\x19MSG_INSTALL_SNAPSHOT_RESP\x10\x0527\n" +
	"\vRaftService\x12(\n" +
	"\x04Step\x12\x0f.distkv.Message\x1a\x0f.distkv.Message2\xcf\x02\n" +
	"\x02KV\x12&\n" +
	"\x03Put\x12\x0e.distkv.PutReq\x1a\x0f.distkv.PutResp\x12&\n" +
	"\x03Get\x12\x0e.distkv.GetReq\x1a\x0f.distkv.GetResp\x12/\n" +
	"\x06Delete\x12\x11.distkv.DeleteReq\x1a\x12.distkv.DeleteResp\x12&\n" +
	"\x03CAS\x12\x0e.distkv.CASReq\x1a\x0f.distkv.CASResp\x12/\n" +
	"\x06Status\x12\x11.distkv.StatusReq\x1a\x12.distkv.StatusResp\x122\n" +
	"\aAddNode\x12\x12.distkv.AddNodeReq\x1a\x13.distkv.AddNodeResp\x12;\n" +
	"\n" +
	"RemoveNode\x12\x15.distkv.RemoveNodeReq\x1a\x16.distkv.RemoveNodeRespB$Z\"github.com/NeilP211/distkv/api;apib\x06proto3"

var (
	file_api_distkv_proto_rawDescOnce sync.Once
	file_api_distkv_proto_rawDescData []byte
)

func file_api_distkv_proto_rawDescGZIP() []byte {
	file_api_distkv_proto_rawDescOnce.Do(func() {
		file_api_distkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_distkv_proto_rawDesc), len(file_api_distkv_proto_rawDesc)))
	})
	return file_api_distkv_proto_rawDescData
}

var file_api_distkv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_distkv_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_distkv_proto_goTypes = []any{
	(EntryType)(0),         // 0: distkv.EntryType
	(MsgType)(0),           // 1: distkv.MsgType
	(*LogEntry)(nil),       // 2: distkv.LogEntry
	(*Snapshot)(nil),       // 3: distkv.Snapshot
	(*Message)(nil),        // 4: distkv.Message
	(*PutReq)(nil),         // 5: distkv.PutReq
	(*PutResp)(nil),        // 6: distkv.PutResp
	(*GetReq)(nil),         // 7: distkv.GetReq
	(*GetResp)(nil),        // 8: distkv.GetResp
	(*DeleteReq)(nil),      // 9: distkv.DeleteReq
	(*DeleteResp)(nil),     // 10: distkv.DeleteResp
	(*CASReq)(nil),         // 11: distkv.CASReq
	(*CASResp)(nil),        // 12: distkv.CASResp
	(*StatusReq)(nil),      // 13: distkv.StatusReq
	(*StatusResp)(nil),     // 14: distkv.StatusResp
	(*AddNodeReq)(nil),     // 15: distkv.AddNodeReq
	(*AddNodeResp)(nil),    // 16: distkv.AddNodeResp
	(*RemoveNodeReq)(nil),  // 17: distkv.RemoveNodeReq
	(*RemoveNodeResp)(nil), // 18: distkv.RemoveNodeResp
}
var file_api_distkv_proto_depIdxs = []int32{
	0,  // 0: distkv.LogEntry.type:type_name -> distkv.EntryType
	1,  // 1: distkv.Message.type:type_name -> distkv.MsgType
	2,  // 2: distkv.Message.entries:type_name -> distkv.LogEntry
	3,  // 3: distkv.Message.snapshot:type_name -> distkv.Snapshot
	4,  // 4: distkv.RaftService.Step:input_type -> distkv.Message
	5,  // 5: distkv.KV.Put:input_type -> distkv.PutReq
	7,  // 6: distkv.KV.Get:input_type -> distkv.GetReq
	9,  // 7: distkv.KV.Delete:input_type -> distkv.DeleteReq
	11, // 8: distkv.KV.CAS:input_type -> distkv.CASReq
	13, // 9: distkv.KV.Status:input_type -> distkv.StatusReq
	15, // 10: distkv.KV.AddNode:input_type -> distkv.AddNodeReq
	17, // 11: distkv.KV.RemoveNode:input_type -> distkv.RemoveNodeReq
	4,  // 12: distkv.RaftService.Step:output_type -> distkv.Message
	6,  // 13: distkv.KV.Put:output_type -> distkv.PutResp
	8,  // 14: distkv.KV.Get:output_type -> distkv.GetResp
	10, // 15: distkv.KV.Delete:output_type -> distkv.DeleteResp
	12, // 16: distkv.KV.CAS:output_type -> distkv.CASResp
	14, // 17: distkv.KV.Status:output_type -> distkv.StatusResp
	16, // 18: distkv.KV.AddNode:output_type -> distkv.AddNodeResp
	18, // 19: distkv.KV.RemoveNode:output_type -> distkv.RemoveNodeResp
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_distkv_proto_init() }
func file_api_distkv_proto_init() {
	if File_api_distkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_distkv_proto_rawDesc), len(file_api_distkv_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_distkv_proto_goTypes,
		DependencyIndexes: file_api_distkv_proto_depIdxs,
		EnumInfos:         file_api_distkv_proto_enumTypes,
		MessageInfos:      file_api_distkv_proto_msgTypes,
	}.Build()
	File_api_distkv_proto = out.File
	file_api_distkv_proto_goTypes = nil
	file_api_distkv_proto_depIdxs = nil
}
